language: scala

sudo: false

scala:
- "2.11.11"

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ${JAVA_HOME} == $(jdk_switcher home oraclejdk8) && "${TRAVIS_BRANCH}" == "master" ]]; then export PUBLISH_SONATYPE=true; fi
  - sbt ++${TRAVIS_SCALA_VERSION} testSequential $(if [[ "${PUBLISH_SONATYPE}" == "true" ]]; then echo "publish" ; fi)

env:
  global:
  - secure: tiIC4c7JuyrRBr/wv1PtqYaCu9Pug3bxmh0keMJK5udbIED4dwjYhoOApMVbLMOw3ofw9+e92rBPSsUd4Hwbtb73SAZsmpjlSLgeh9vNmgXCHaIEA/NBrQi/00eoeOWnNx68C03CkGQgNhDcZP6YXCKq+MZKjYt0efGQAoOLk4w=
  - secure: Vlr46mkQgp9lif7brxGVUgAegLM0IZI+srDYJJsOmNtMnU8um0SmwXAjVU8K4j+95bCpEdRlU6FKlVQw63Kv4P1hTssawFrBTXT5xeLBHKCIetZC67+gcdmDMOa/c1Q31jpVrPXQ7jVXCNqmkRiYzuoeTl96IifmarBxDM9hGkY=

matrix:
  include:
  - scala: "2.12.2"
    jdk: oraclejdk8
  - dist: trusty
    group: edge
    sudo: required
    scala: "2.12.2"
    jdk: oraclejdk9
    script:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - sbt package
    - jdk_switcher use oraclejdk9
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION testSequential
