language: scala

sudo: false

scala:
- "2.11.12"
- "2.12.8"
- "2.13.0-RC2"

jdk:
  - oraclejdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++${TRAVIS_SCALA_VERSION}!" testSequential

matrix:
  include:
  - scala: "2.11.12"
    jdk: oraclejdk8
    sudo: required
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt "++${TRAVIS_SCALA_VERSION}!" "msgpack4z-argonautNative/test:nativeLink"
  - scala: "2.12.8"
    jdk: openjdk11
    dist: xenial

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
